# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170719_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 19, 9, 41, 0, 494808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=home.models.User, on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
